KISSY.add(function(S,require,exports,module){
/*compiled by xtemplate#3.3.3*/
var ret = module.exports = function personConfigView(undefined){
var t;
var t0;
var t1;
var t2;
var t3;
var t4;
var t5;
var t6;
var t7;
var t8;
var t9;
var tpl = this;
var root = tpl.root;
var buffer = tpl.buffer;
var scope = tpl.scope;
var runtime = tpl.runtime;
var name = tpl.name;
var pos = tpl.pos;
var data = scope.data;
var affix = scope.affix;
var nativeCommands = root.nativeCommands;
var utils = root.utils;
var callFnUtil = utils["callFn"];
var callCommandUtil = utils["callCommand"];
var rangeCommand = nativeCommands["range"];
var foreachCommand = nativeCommands["foreach"];
var forinCommand = nativeCommands["forin"];
var eachCommand = nativeCommands["each"];
var withCommand = nativeCommands["with"];
var ifCommand = nativeCommands["if"];
var setCommand = nativeCommands["set"];
var includeCommand = nativeCommands["include"];
var parseCommand = nativeCommands["parse"];
var extendCommand = nativeCommands["extend"];
var blockCommand = nativeCommands["block"];
var macroCommand = nativeCommands["macro"];
var debuggerCommand = nativeCommands["debugger"];


buffer.data += '<form class="form-horizontal" id="resetPass" method="post" action="">\n    <div class="control-group">\n        <label class="control-label" for="eamil">账号</label>\n\n        <div class="controls">\n            <input type="text" class="input" name="email" id="eamil" value="';
pos.line = 6;
var id0 = ((t=(affix.account)) !== undefined ? affix.account.email:((t = data.account) !== undefined ? (t.email) :scope.resolveLooseUp(["account","email"])));
buffer = buffer.writeEscaped(id0);
buffer.data += '" readonly="readonly">\n        </div>\n    </div>\n    <div class="control-group">\n        <label class="control-label" for="eamil">角色</label>\n\n        <div class="controls">\n            <input type="text" class="input" name="role" id="role" value="';
pos.line = 13;
var id1 = ((t=(affix.account)) !== undefined ? affix.account.accountRole[0].role.name:((t = data.account) !== undefined ? ((t0=t.accountRole) != null?((t1=t0[0]) != null?((t2=t1.role) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["account","accountRole",0,"role","name"])));
buffer = buffer.writeEscaped(id1);
buffer.data += '"\n                   readonly="readonly">\n        </div>\n    </div>\n    <div class="control-group">\n        <label class="control-label" for="eamil">所属单位</label>\n\n        <div class="controls">\n            <input type="text" class="input" name="company" id="company" value="';
pos.line = 21;
var id2 = ((t=(affix.account)) !== undefined ? affix.account.companyName:((t = data.account) !== undefined ? (t.companyName) :scope.resolveLooseUp(["account","companyName"])));
buffer = buffer.writeEscaped(id2);
buffer.data += '"\n                   readonly="readonly">\n        </div>\n    </div>\n    <div class="control-group">\n        <label class="control-label" for="eamil">名称</label>\n\n        <div class="controls">\n            <input type="text" class="input" name="name" id="name" value="';
pos.line = 29;
var id3 = ((t=(affix.account)) !== undefined ? affix.account.name:((t = data.account) !== undefined ? (t.name) :scope.resolveLooseUp(["account","name"])));
buffer = buffer.writeEscaped(id3);
buffer.data += '">\n        </div>\n    </div>\n    <div class="control-group">\n        <label class="control-label" for="password">输入密码</label>\n\n        <div class="controls">\n            <input type="password" class="input" required="required" required-msg="密码不能为空" name="password"\n                   id="password" placeholder="请输入密码" safe-password="safe-password" password-min-len="6"\n                   password-max-len="10">\n        </div>\n    </div>\n    <div class="control-group">\n        <label class="control-label" for="again-password">再次输入密码</label>\n\n        <div class="controls">\n            <input type="password" class="input" id="again-password" name="again-password"\n                   equal-field="password" required="required" required-msg="再次输入密码不能为空" placeholder="请再次输入密码">\n        </div>\n    </div>\n    <div class="form-actions">\n        <input class="ks-button ks-button-primary ks-button-shown" type="submit" value="提交">\n    </div>\n</form>';
return buffer;
};
ret.TPL_NAME = module.id || module.name;
});