KISSY.add(function(S,require,exports,module){
/*compiled by xtemplate#3.3.3*/
var ret = module.exports = function personConfigView(undefined){
var t;
var t0;
var t1;
var t2;
var t3;
var t4;
var t5;
var t6;
var t7;
var t8;
var t9;
var tpl = this;
var root = tpl.root;
var buffer = tpl.buffer;
var scope = tpl.scope;
var runtime = tpl.runtime;
var name = tpl.name;
var pos = tpl.pos;
var data = scope.data;
var affix = scope.affix;
var nativeCommands = root.nativeCommands;
var utils = root.utils;
var callFnUtil = utils["callFn"];
var callCommandUtil = utils["callCommand"];
var rangeCommand = nativeCommands["range"];
var foreachCommand = nativeCommands["foreach"];
var forinCommand = nativeCommands["forin"];
var eachCommand = nativeCommands["each"];
var withCommand = nativeCommands["with"];
var ifCommand = nativeCommands["if"];
var setCommand = nativeCommands["set"];
var includeCommand = nativeCommands["include"];
var parseCommand = nativeCommands["parse"];
var extendCommand = nativeCommands["extend"];
var blockCommand = nativeCommands["block"];
var macroCommand = nativeCommands["macro"];
var debuggerCommand = nativeCommands["debugger"];


buffer.data += '<form class="form-horizontal" id="personConfig" method="post" action="a">\n    <div class="control-group">\n        <label class="control-label" for="eamil">账号，角色，所在单位</label>\n        <div class="controls">\n            <input type="text" class="input-small" name="email" id="eamil" value="';
pos.line = 5;
var id0 = ((t=(affix.account)) !== undefined ? affix.account.email:((t = data.account) !== undefined ? (t.email) :scope.resolveLooseUp(["account","email"])));
buffer = buffer.writeEscaped(id0);
buffer.data += '" readonly="readonly">\n            <input type="text" class="input-small" name="role" id="role" value="';
pos.line = 6;
var id1 = ((t=(affix.account)) !== undefined ? affix.account.accountRole[0].role.name:((t = data.account) !== undefined ? ((t0=t.accountRole) != null?((t1=t0[0]) != null?((t2=t1.role) != null?(t2.name):t2):t1):t0) :scope.resolveLooseUp(["account","accountRole",0,"role","name"])));
buffer = buffer.writeEscaped(id1);
buffer.data += '"\n                   readonly="readonly">\n            <input type="text" class="input-mini" name="company" id="company" value="';
pos.line = 8;
var id2 = ((t=(affix.account)) !== undefined ? affix.account.companyName:((t = data.account) !== undefined ? (t.companyName) :scope.resolveLooseUp(["account","companyName"])));
buffer = buffer.writeEscaped(id2);
buffer.data += '"\n                   readonly="readonly">\n        </div>\n    </div>\n    <div class="control-group">\n        <label class="control-label" for="eamil">名称</label>\n\n        <div class="controls">\n            <input type="text" class="input-medium" name="personConfig_name" max-len="8" max-len-msg="名称不能多于8个字符"\n                   id="personConfig_name" required="" safe-name="safe-name"\n                   required-msg="名称不能为空" msg-wrapper="#personConfig_u145"\n                   value="';
pos.line = 19;
var id3 = ((t=(affix.account)) !== undefined ? affix.account.name:((t = data.account) !== undefined ? (t.name) :scope.resolveLooseUp(["account","name"])));
buffer = buffer.writeEscaped(id3);
buffer.data += '" readonly="readonly">\n            <input hidden="hidden" id="personConfig_name_hidden" name="personConfig_name_hidden"\n                   updateName-Cancel="updateName-Cancel" updateName-confirm="updateName-confirm"\n                   class="" msg-wrapper="#personConfig_u145"/>\n        </div>\n\n        <div id="personConfig_u102" class="ax_shape">\n            <img id="personConfig_u102_img" class="img " src="./account/images/editProject/add_project_button_u73.png"/>\n            <!-- Unnamed () -->\n            <div id="personConfig_u103" class="text">\n                <p><span id="personConfig_u103_txt">编辑</span></p>\n            </div>\n        </div>\n    </div>\n    <input hidden="hidden" needAFail="needAFail"/>\n\n    <div id="personConfig_u145" class="ax_paragraph logintitle"/>\n</form>\n<form class="form-horizontal" id="personConfig2" method="post" action="a">\n    <div class="control-group">\n        <label class="control-label" for="personConfig_password">输入新密码</label>\n\n        <div class="controls">\n            <input type="password" class="input-medium" required="required"\n                   required-msg="密码不能为空" name="personConfig_password"\n                   id="personConfig_password" placeholder="请输入密码" safe-password="safe-password" min-len="6"\n                   min-len-msg="密码不能少于6个字符"\n                   max-len="10" max-len-msg="密码不能多于10个字符" disabled="disabled" msg-wrapper="#personConfig_u146">\n        </div>\n    </div>\n    <div class="control-group">\n        <label class="control-label" for="personConfig_again-password">再次输入新密码</label>\n\n        <div class="controls">\n            <input type="password" class="input-medium" id="personConfig_again-password"\n                   name="personConfig_again-password"\n                   equal-field="personConfig_password" required="required" required-msg="再次输入密码不能为空"\n                   placeholder="请再次输入密码"\n                   disabled="disabled" msg-wrapper="#personConfig_u146">\n            <input hidden="hidden" name="personConfig_password_hidden"\n                   updatePassword-Cancel="updatePassword-Cancel" updatePassword-confirm="updatePassword-confirm"\n                   class="" msg-wrapper="#personConfig_u146"/>\n        </div>\n    </div>\n    <div id="personConfig_u104" class="ax_shape">\n        <img id="personConfig_u104_img" class="img " src="./account/images/editProject/add_project_button_u73.png"/>\n        <!-- Unnamed () -->\n        <div id="personConfig_u105" class="text">\n            <p><span id="personConfig_u105_txt">编辑</span></p>\n        </div>\n    </div>\n    <input hidden="hidden" needAFail="needAFail"/>\n\n    <div id="personConfig_u146" class="ax_paragraph logintitle"/>\n</form>';
return buffer;
};
ret.TPL_NAME = module.id || module.name;
});